
:- module(number_words,
          [number_word/2]).

number_word(N, W, english) :- number_word(N, W). 

number_word(1, [one]).
number_word(2, [two]).
number_word(3, [three]).
number_word(4, [four]).
number_word(5, [five]).
number_word(6, [six]).
number_word(7, [seven]).
number_word(8, [eight]).
number_word(9, [nine]).
number_word(10, [ten]).
number_word(11, [eleven]).
number_word(12, [twelve]).
number_word(13, [thirteen]).
number_word(14, [fourteen]).
number_word(15, [fifteen]).
number_word(16, [sixteen]).
number_word(17, [seventeen]).
number_word(18, [eighteen]).
number_word(19, [nineteen]).
number_word(20, [twenty]).
number_word(21, [twenty,one]).
number_word(22, [twenty,two]).
number_word(23, [twenty,three]).
number_word(24, [twenty,four]).
number_word(25, [twenty,five]).
number_word(26, [twenty,six]).
number_word(27, [twenty,seven]).
number_word(28, [twenty,eight]).
number_word(29, [twenty,nine]).
number_word(30, [thirty]).
number_word(31, [thirty,one]).
number_word(32, [thirty,two]).
number_word(33, [thirty,three]).
number_word(34, [thirty,four]).
number_word(35, [thirty,five]).
number_word(36, [thirty,six]).
number_word(37, [thirty,seven]).
number_word(38, [thirty,eight]).
number_word(39, [thirty,nine]).
number_word(40, [forty]).
number_word(41, [forty,one]).
number_word(42, [forty,two]).
number_word(43, [forty,three]).
number_word(44, [forty,four]).
number_word(45, [forty,five]).
number_word(46, [forty,six]).
number_word(47, [forty,seven]).
number_word(48, [forty,eight]).
number_word(49, [forty,nine]).
number_word(50, [fifty]).
number_word(51, [fifty,one]).
number_word(52, [fifty,two]).
number_word(53, [fifty,three]).
number_word(54, [fifty,four]).
number_word(55, [fifty,five]).
number_word(56, [fifty,six]).
number_word(57, [fifty,seven]).
number_word(58, [fifty,eight]).
number_word(59, [fifty,nine]).
number_word(60, [sixty]).
number_word(61, [sixty,one]).
number_word(62, [sixty,two]).
number_word(63, [sixty,three]).
number_word(64, [sixty,four]).
number_word(65, [sixty,five]).
number_word(66, [sixty,six]).
number_word(67, [sixty,seven]).
number_word(68, [sixty,eight]).
number_word(69, [sixty,nine]).
number_word(70, [seventy]).
number_word(71, [seventy,one]).
number_word(72, [seventy,two]).
number_word(73, [seventy,three]).
number_word(74, [seventy,four]).
number_word(75, [seventy,five]).
number_word(76, [seventy,six]).
number_word(77, [seventy,seven]).
number_word(78, [seventy,eight]).
number_word(79, [seventy,nine]).
number_word(80, [eighty]).
number_word(81, [eighty,one]).
number_word(82, [eighty,two]).
number_word(83, [eighty,three]).
number_word(84, [eighty,four]).
number_word(85, [eighty,five]).
number_word(86, [eighty,six]).
number_word(87, [eighty,seven]).
number_word(88, [eighty,eight]).
number_word(89, [eighty,nine]).
number_word(90, [ninety]).
number_word(91, [ninety,one]).
number_word(92, [ninety,two]).
number_word(93, [ninety,three]).
number_word(94, [ninety,four]).
number_word(95, [ninety,five]).
number_word(96, [ninety,six]).
number_word(97, [ninety,seven]).
number_word(98, [ninety,eight]).
number_word(99, [ninety,nine]).
number_word(100, [one,hundred]).
number_word(101, [one,hundred,one]).
number_word(102, [one,hundred,two]).
number_word(103, [one,hundred,three]).
number_word(104, [one,hundred,four]).
number_word(105, [one,hundred,five]).
number_word(106, [one,hundred,six]).
number_word(107, [one,hundred,seven]).
number_word(108, [one,hundred,eight]).
number_word(109, [one,hundred,nine]).
number_word(110, [one,hundred,ten]).
number_word(111, [one,hundred,eleven]).
number_word(112, [one,hundred,twelve]).
number_word(113, [one,hundred,thirteen]).
number_word(114, [one,hundred,fourteen]).
number_word(115, [one,hundred,fifteen]).
number_word(116, [one,hundred,sixteen]).
number_word(117, [one,hundred,seventeen]).
number_word(118, [one,hundred,eighteen]).
number_word(119, [one,hundred,nineteen]).
number_word(120, [one,hundred,twenty]).
number_word(121, [one,hundred,twenty,one]).
number_word(122, [one,hundred,twenty,two]).
number_word(123, [one,hundred,twenty,three]).
number_word(124, [one,hundred,twenty,four]).
number_word(125, [one,hundred,twenty,five]).
number_word(126, [one,hundred,twenty,six]).
number_word(127, [one,hundred,twenty,seven]).
number_word(128, [one,hundred,twenty,eight]).
number_word(129, [one,hundred,twenty,nine]).
number_word(130, [one,hundred,thirty]).
number_word(131, [one,hundred,thirty,one]).
number_word(132, [one,hundred,thirty,two]).
number_word(133, [one,hundred,thirty,three]).
number_word(134, [one,hundred,thirty,four]).
number_word(135, [one,hundred,thirty,five]).
number_word(136, [one,hundred,thirty,six]).
number_word(137, [one,hundred,thirty,seven]).
number_word(138, [one,hundred,thirty,eight]).
number_word(139, [one,hundred,thirty,nine]).
number_word(140, [one,hundred,forty]).
number_word(141, [one,hundred,forty,one]).
number_word(142, [one,hundred,forty,two]).
number_word(143, [one,hundred,forty,three]).
number_word(144, [one,hundred,forty,four]).
number_word(145, [one,hundred,forty,five]).
number_word(146, [one,hundred,forty,six]).
number_word(147, [one,hundred,forty,seven]).
number_word(148, [one,hundred,forty,eight]).
number_word(149, [one,hundred,forty,nine]).
number_word(150, [one,hundred,fifty]).
number_word(151, [one,hundred,fifty,one]).
number_word(152, [one,hundred,fifty,two]).
number_word(153, [one,hundred,fifty,three]).
number_word(154, [one,hundred,fifty,four]).
number_word(155, [one,hundred,fifty,five]).
number_word(156, [one,hundred,fifty,six]).
number_word(157, [one,hundred,fifty,seven]).
number_word(158, [one,hundred,fifty,eight]).
number_word(159, [one,hundred,fifty,nine]).
number_word(160, [one,hundred,sixty]).
number_word(161, [one,hundred,sixty,one]).
number_word(162, [one,hundred,sixty,two]).
number_word(163, [one,hundred,sixty,three]).
number_word(164, [one,hundred,sixty,four]).
number_word(165, [one,hundred,sixty,five]).
number_word(166, [one,hundred,sixty,six]).
number_word(167, [one,hundred,sixty,seven]).
number_word(168, [one,hundred,sixty,eight]).
number_word(169, [one,hundred,sixty,nine]).
number_word(170, [one,hundred,seventy]).
number_word(171, [one,hundred,seventy,one]).
number_word(172, [one,hundred,seventy,two]).
number_word(173, [one,hundred,seventy,three]).
number_word(174, [one,hundred,seventy,four]).
number_word(175, [one,hundred,seventy,five]).
number_word(176, [one,hundred,seventy,six]).
number_word(177, [one,hundred,seventy,seven]).
number_word(178, [one,hundred,seventy,eight]).
number_word(179, [one,hundred,seventy,nine]).
number_word(180, [one,hundred,eighty]).
number_word(181, [one,hundred,eighty,one]).
number_word(182, [one,hundred,eighty,two]).
number_word(183, [one,hundred,eighty,three]).
number_word(184, [one,hundred,eighty,four]).
number_word(185, [one,hundred,eighty,five]).
number_word(186, [one,hundred,eighty,six]).
number_word(187, [one,hundred,eighty,seven]).
number_word(188, [one,hundred,eighty,eight]).
number_word(189, [one,hundred,eighty,nine]).
number_word(190, [one,hundred,ninety]).
number_word(191, [one,hundred,ninety,one]).
number_word(192, [one,hundred,ninety,two]).
number_word(193, [one,hundred,ninety,three]).
number_word(194, [one,hundred,ninety,four]).
number_word(195, [one,hundred,ninety,five]).
number_word(196, [one,hundred,ninety,six]).
number_word(197, [one,hundred,ninety,seven]).
number_word(198, [one,hundred,ninety,eight]).
number_word(199, [one,hundred,ninety,nine]).
number_word(200, [two,hundred]).
number_word(201, [two,hundred,one]).
number_word(202, [two,hundred,two]).
number_word(203, [two,hundred,three]).
number_word(204, [two,hundred,four]).
number_word(205, [two,hundred,five]).
number_word(206, [two,hundred,six]).
number_word(207, [two,hundred,seven]).
number_word(208, [two,hundred,eight]).
number_word(209, [two,hundred,nine]).
number_word(210, [two,hundred,ten]).
number_word(211, [two,hundred,eleven]).
number_word(212, [two,hundred,twelve]).
number_word(213, [two,hundred,thirteen]).
number_word(214, [two,hundred,fourteen]).
number_word(215, [two,hundred,fifteen]).
number_word(216, [two,hundred,sixteen]).
number_word(217, [two,hundred,seventeen]).
number_word(218, [two,hundred,eighteen]).
number_word(219, [two,hundred,nineteen]).
number_word(220, [two,hundred,twenty]).
number_word(221, [two,hundred,twenty,one]).
number_word(222, [two,hundred,twenty,two]).
number_word(223, [two,hundred,twenty,three]).
number_word(224, [two,hundred,twenty,four]).
number_word(225, [two,hundred,twenty,five]).
number_word(226, [two,hundred,twenty,six]).
number_word(227, [two,hundred,twenty,seven]).
number_word(228, [two,hundred,twenty,eight]).
number_word(229, [two,hundred,twenty,nine]).
number_word(230, [two,hundred,thirty]).
number_word(231, [two,hundred,thirty,one]).
number_word(232, [two,hundred,thirty,two]).
number_word(233, [two,hundred,thirty,three]).
number_word(234, [two,hundred,thirty,four]).
number_word(235, [two,hundred,thirty,five]).
number_word(236, [two,hundred,thirty,six]).
number_word(237, [two,hundred,thirty,seven]).
number_word(238, [two,hundred,thirty,eight]).
number_word(239, [two,hundred,thirty,nine]).
number_word(240, [two,hundred,forty]).
number_word(241, [two,hundred,forty,one]).
number_word(242, [two,hundred,forty,two]).
number_word(243, [two,hundred,forty,three]).
number_word(244, [two,hundred,forty,four]).
number_word(245, [two,hundred,forty,five]).
number_word(246, [two,hundred,forty,six]).
number_word(247, [two,hundred,forty,seven]).
number_word(248, [two,hundred,forty,eight]).
number_word(249, [two,hundred,forty,nine]).
number_word(250, [two,hundred,fifty]).
number_word(251, [two,hundred,fifty,one]).
number_word(252, [two,hundred,fifty,two]).
number_word(253, [two,hundred,fifty,three]).
number_word(254, [two,hundred,fifty,four]).
number_word(255, [two,hundred,fifty,five]).
number_word(256, [two,hundred,fifty,six]).
number_word(257, [two,hundred,fifty,seven]).
number_word(258, [two,hundred,fifty,eight]).
number_word(259, [two,hundred,fifty,nine]).
number_word(260, [two,hundred,sixty]).
number_word(261, [two,hundred,sixty,one]).
number_word(262, [two,hundred,sixty,two]).
number_word(263, [two,hundred,sixty,three]).
number_word(264, [two,hundred,sixty,four]).
number_word(265, [two,hundred,sixty,five]).
number_word(266, [two,hundred,sixty,six]).
number_word(267, [two,hundred,sixty,seven]).
number_word(268, [two,hundred,sixty,eight]).
number_word(269, [two,hundred,sixty,nine]).
number_word(270, [two,hundred,seventy]).
number_word(271, [two,hundred,seventy,one]).
number_word(272, [two,hundred,seventy,two]).
number_word(273, [two,hundred,seventy,three]).
number_word(274, [two,hundred,seventy,four]).
number_word(275, [two,hundred,seventy,five]).
number_word(276, [two,hundred,seventy,six]).
number_word(277, [two,hundred,seventy,seven]).
number_word(278, [two,hundred,seventy,eight]).
number_word(279, [two,hundred,seventy,nine]).
number_word(280, [two,hundred,eighty]).
number_word(281, [two,hundred,eighty,one]).
number_word(282, [two,hundred,eighty,two]).
number_word(283, [two,hundred,eighty,three]).
number_word(284, [two,hundred,eighty,four]).
number_word(285, [two,hundred,eighty,five]).
number_word(286, [two,hundred,eighty,six]).
number_word(287, [two,hundred,eighty,seven]).
number_word(288, [two,hundred,eighty,eight]).
number_word(289, [two,hundred,eighty,nine]).
number_word(290, [two,hundred,ninety]).
number_word(291, [two,hundred,ninety,one]).
number_word(292, [two,hundred,ninety,two]).
number_word(293, [two,hundred,ninety,three]).
number_word(294, [two,hundred,ninety,four]).
number_word(295, [two,hundred,ninety,five]).
number_word(296, [two,hundred,ninety,six]).
number_word(297, [two,hundred,ninety,seven]).
number_word(298, [two,hundred,ninety,eight]).
number_word(299, [two,hundred,ninety,nine]).
number_word(300, [three,hundred]).
number_word(301, [three,hundred,one]).
number_word(302, [three,hundred,two]).
number_word(303, [three,hundred,three]).
number_word(304, [three,hundred,four]).
number_word(305, [three,hundred,five]).
number_word(306, [three,hundred,six]).
number_word(307, [three,hundred,seven]).
number_word(308, [three,hundred,eight]).
number_word(309, [three,hundred,nine]).
number_word(310, [three,hundred,ten]).
number_word(311, [three,hundred,eleven]).
number_word(312, [three,hundred,twelve]).
number_word(313, [three,hundred,thirteen]).
number_word(314, [three,hundred,fourteen]).
number_word(315, [three,hundred,fifteen]).
number_word(316, [three,hundred,sixteen]).
number_word(317, [three,hundred,seventeen]).
number_word(318, [three,hundred,eighteen]).
number_word(319, [three,hundred,nineteen]).
number_word(320, [three,hundred,twenty]).
number_word(321, [three,hundred,twenty,one]).
number_word(322, [three,hundred,twenty,two]).
number_word(323, [three,hundred,twenty,three]).
number_word(324, [three,hundred,twenty,four]).
number_word(325, [three,hundred,twenty,five]).
number_word(326, [three,hundred,twenty,six]).
number_word(327, [three,hundred,twenty,seven]).
number_word(328, [three,hundred,twenty,eight]).
number_word(329, [three,hundred,twenty,nine]).
number_word(330, [three,hundred,thirty]).
number_word(331, [three,hundred,thirty,one]).
number_word(332, [three,hundred,thirty,two]).
number_word(333, [three,hundred,thirty,three]).
number_word(334, [three,hundred,thirty,four]).
number_word(335, [three,hundred,thirty,five]).
number_word(336, [three,hundred,thirty,six]).
number_word(337, [three,hundred,thirty,seven]).
number_word(338, [three,hundred,thirty,eight]).
number_word(339, [three,hundred,thirty,nine]).
number_word(340, [three,hundred,forty]).
number_word(341, [three,hundred,forty,one]).
number_word(342, [three,hundred,forty,two]).
number_word(343, [three,hundred,forty,three]).
number_word(344, [three,hundred,forty,four]).
number_word(345, [three,hundred,forty,five]).
number_word(346, [three,hundred,forty,six]).
number_word(347, [three,hundred,forty,seven]).
number_word(348, [three,hundred,forty,eight]).
number_word(349, [three,hundred,forty,nine]).
number_word(350, [three,hundred,fifty]).
number_word(351, [three,hundred,fifty,one]).
number_word(352, [three,hundred,fifty,two]).
number_word(353, [three,hundred,fifty,three]).
number_word(354, [three,hundred,fifty,four]).
number_word(355, [three,hundred,fifty,five]).
number_word(356, [three,hundred,fifty,six]).
number_word(357, [three,hundred,fifty,seven]).
number_word(358, [three,hundred,fifty,eight]).
number_word(359, [three,hundred,fifty,nine]).
number_word(360, [three,hundred,sixty]).
number_word(361, [three,hundred,sixty,one]).
number_word(362, [three,hundred,sixty,two]).
number_word(363, [three,hundred,sixty,three]).
number_word(364, [three,hundred,sixty,four]).
number_word(365, [three,hundred,sixty,five]).
number_word(366, [three,hundred,sixty,six]).
number_word(367, [three,hundred,sixty,seven]).
number_word(368, [three,hundred,sixty,eight]).
number_word(369, [three,hundred,sixty,nine]).
number_word(370, [three,hundred,seventy]).
number_word(371, [three,hundred,seventy,one]).
number_word(372, [three,hundred,seventy,two]).
number_word(373, [three,hundred,seventy,three]).
number_word(374, [three,hundred,seventy,four]).
number_word(375, [three,hundred,seventy,five]).
number_word(376, [three,hundred,seventy,six]).
number_word(377, [three,hundred,seventy,seven]).
number_word(378, [three,hundred,seventy,eight]).
number_word(379, [three,hundred,seventy,nine]).
number_word(380, [three,hundred,eighty]).
number_word(381, [three,hundred,eighty,one]).
number_word(382, [three,hundred,eighty,two]).
number_word(383, [three,hundred,eighty,three]).
number_word(384, [three,hundred,eighty,four]).
number_word(385, [three,hundred,eighty,five]).
number_word(386, [three,hundred,eighty,six]).
number_word(387, [three,hundred,eighty,seven]).
number_word(388, [three,hundred,eighty,eight]).
number_word(389, [three,hundred,eighty,nine]).
number_word(390, [three,hundred,ninety]).
number_word(391, [three,hundred,ninety,one]).
number_word(392, [three,hundred,ninety,two]).
number_word(393, [three,hundred,ninety,three]).
number_word(394, [three,hundred,ninety,four]).
number_word(395, [three,hundred,ninety,five]).
number_word(396, [three,hundred,ninety,six]).
number_word(397, [three,hundred,ninety,seven]).
number_word(398, [three,hundred,ninety,eight]).
number_word(399, [three,hundred,ninety,nine]).
number_word(400, [four,hundred]).
number_word(401, [four,hundred,one]).
number_word(402, [four,hundred,two]).
number_word(403, [four,hundred,three]).
number_word(404, [four,hundred,four]).
number_word(405, [four,hundred,five]).
number_word(406, [four,hundred,six]).
number_word(407, [four,hundred,seven]).
number_word(408, [four,hundred,eight]).
number_word(409, [four,hundred,nine]).
number_word(410, [four,hundred,ten]).
number_word(411, [four,hundred,eleven]).
number_word(412, [four,hundred,twelve]).
number_word(413, [four,hundred,thirteen]).
number_word(414, [four,hundred,fourteen]).
number_word(415, [four,hundred,fifteen]).
number_word(416, [four,hundred,sixteen]).
number_word(417, [four,hundred,seventeen]).
number_word(418, [four,hundred,eighteen]).
number_word(419, [four,hundred,nineteen]).
number_word(420, [four,hundred,twenty]).
number_word(421, [four,hundred,twenty,one]).
number_word(422, [four,hundred,twenty,two]).
number_word(423, [four,hundred,twenty,three]).
number_word(424, [four,hundred,twenty,four]).
number_word(425, [four,hundred,twenty,five]).
number_word(426, [four,hundred,twenty,six]).
number_word(427, [four,hundred,twenty,seven]).
number_word(428, [four,hundred,twenty,eight]).
number_word(429, [four,hundred,twenty,nine]).
number_word(430, [four,hundred,thirty]).
number_word(431, [four,hundred,thirty,one]).
number_word(432, [four,hundred,thirty,two]).
number_word(433, [four,hundred,thirty,three]).
number_word(434, [four,hundred,thirty,four]).
number_word(435, [four,hundred,thirty,five]).
number_word(436, [four,hundred,thirty,six]).
number_word(437, [four,hundred,thirty,seven]).
number_word(438, [four,hundred,thirty,eight]).
number_word(439, [four,hundred,thirty,nine]).
number_word(440, [four,hundred,forty]).
number_word(441, [four,hundred,forty,one]).
number_word(442, [four,hundred,forty,two]).
number_word(443, [four,hundred,forty,three]).
number_word(444, [four,hundred,forty,four]).
number_word(445, [four,hundred,forty,five]).
number_word(446, [four,hundred,forty,six]).
number_word(447, [four,hundred,forty,seven]).
number_word(448, [four,hundred,forty,eight]).
number_word(449, [four,hundred,forty,nine]).
number_word(450, [four,hundred,fifty]).
number_word(451, [four,hundred,fifty,one]).
number_word(452, [four,hundred,fifty,two]).
number_word(453, [four,hundred,fifty,three]).
number_word(454, [four,hundred,fifty,four]).
number_word(455, [four,hundred,fifty,five]).
number_word(456, [four,hundred,fifty,six]).
number_word(457, [four,hundred,fifty,seven]).
number_word(458, [four,hundred,fifty,eight]).
number_word(459, [four,hundred,fifty,nine]).
number_word(460, [four,hundred,sixty]).
number_word(461, [four,hundred,sixty,one]).
number_word(462, [four,hundred,sixty,two]).
number_word(463, [four,hundred,sixty,three]).
number_word(464, [four,hundred,sixty,four]).
number_word(465, [four,hundred,sixty,five]).
number_word(466, [four,hundred,sixty,six]).
number_word(467, [four,hundred,sixty,seven]).
number_word(468, [four,hundred,sixty,eight]).
number_word(469, [four,hundred,sixty,nine]).
number_word(470, [four,hundred,seventy]).
number_word(471, [four,hundred,seventy,one]).
number_word(472, [four,hundred,seventy,two]).
number_word(473, [four,hundred,seventy,three]).
number_word(474, [four,hundred,seventy,four]).
number_word(475, [four,hundred,seventy,five]).
number_word(476, [four,hundred,seventy,six]).
number_word(477, [four,hundred,seventy,seven]).
number_word(478, [four,hundred,seventy,eight]).
number_word(479, [four,hundred,seventy,nine]).
number_word(480, [four,hundred,eighty]).
number_word(481, [four,hundred,eighty,one]).
number_word(482, [four,hundred,eighty,two]).
number_word(483, [four,hundred,eighty,three]).
number_word(484, [four,hundred,eighty,four]).
number_word(485, [four,hundred,eighty,five]).
number_word(486, [four,hundred,eighty,six]).
number_word(487, [four,hundred,eighty,seven]).
number_word(488, [four,hundred,eighty,eight]).
number_word(489, [four,hundred,eighty,nine]).
number_word(490, [four,hundred,ninety]).
number_word(491, [four,hundred,ninety,one]).
number_word(492, [four,hundred,ninety,two]).
number_word(493, [four,hundred,ninety,three]).
number_word(494, [four,hundred,ninety,four]).
number_word(495, [four,hundred,ninety,five]).
number_word(496, [four,hundred,ninety,six]).
number_word(497, [four,hundred,ninety,seven]).
number_word(498, [four,hundred,ninety,eight]).
number_word(499, [four,hundred,ninety,nine]).
number_word(500, [five,hundred]).
number_word(501, [five,hundred,one]).
number_word(502, [five,hundred,two]).
number_word(503, [five,hundred,three]).
number_word(504, [five,hundred,four]).
number_word(505, [five,hundred,five]).
number_word(506, [five,hundred,six]).
number_word(507, [five,hundred,seven]).
number_word(508, [five,hundred,eight]).
number_word(509, [five,hundred,nine]).
number_word(510, [five,hundred,ten]).
number_word(511, [five,hundred,eleven]).
number_word(512, [five,hundred,twelve]).
number_word(513, [five,hundred,thirteen]).
number_word(514, [five,hundred,fourteen]).
number_word(515, [five,hundred,fifteen]).
number_word(516, [five,hundred,sixteen]).
number_word(517, [five,hundred,seventeen]).
number_word(518, [five,hundred,eighteen]).
number_word(519, [five,hundred,nineteen]).
number_word(520, [five,hundred,twenty]).
number_word(521, [five,hundred,twenty,one]).
number_word(522, [five,hundred,twenty,two]).
number_word(523, [five,hundred,twenty,three]).
number_word(524, [five,hundred,twenty,four]).
number_word(525, [five,hundred,twenty,five]).
number_word(526, [five,hundred,twenty,six]).
number_word(527, [five,hundred,twenty,seven]).
number_word(528, [five,hundred,twenty,eight]).
number_word(529, [five,hundred,twenty,nine]).
number_word(530, [five,hundred,thirty]).
number_word(531, [five,hundred,thirty,one]).
number_word(532, [five,hundred,thirty,two]).
number_word(533, [five,hundred,thirty,three]).
number_word(534, [five,hundred,thirty,four]).
number_word(535, [five,hundred,thirty,five]).
number_word(536, [five,hundred,thirty,six]).
number_word(537, [five,hundred,thirty,seven]).
number_word(538, [five,hundred,thirty,eight]).
number_word(539, [five,hundred,thirty,nine]).
number_word(540, [five,hundred,forty]).
number_word(541, [five,hundred,forty,one]).
number_word(542, [five,hundred,forty,two]).
number_word(543, [five,hundred,forty,three]).
number_word(544, [five,hundred,forty,four]).
number_word(545, [five,hundred,forty,five]).
number_word(546, [five,hundred,forty,six]).
number_word(547, [five,hundred,forty,seven]).
number_word(548, [five,hundred,forty,eight]).
number_word(549, [five,hundred,forty,nine]).
number_word(550, [five,hundred,fifty]).
number_word(551, [five,hundred,fifty,one]).
number_word(552, [five,hundred,fifty,two]).
number_word(553, [five,hundred,fifty,three]).
number_word(554, [five,hundred,fifty,four]).
number_word(555, [five,hundred,fifty,five]).
number_word(556, [five,hundred,fifty,six]).
number_word(557, [five,hundred,fifty,seven]).
number_word(558, [five,hundred,fifty,eight]).
number_word(559, [five,hundred,fifty,nine]).
number_word(560, [five,hundred,sixty]).
number_word(561, [five,hundred,sixty,one]).
number_word(562, [five,hundred,sixty,two]).
number_word(563, [five,hundred,sixty,three]).
number_word(564, [five,hundred,sixty,four]).
number_word(565, [five,hundred,sixty,five]).
number_word(566, [five,hundred,sixty,six]).
number_word(567, [five,hundred,sixty,seven]).
number_word(568, [five,hundred,sixty,eight]).
number_word(569, [five,hundred,sixty,nine]).
number_word(570, [five,hundred,seventy]).
number_word(571, [five,hundred,seventy,one]).
number_word(572, [five,hundred,seventy,two]).
number_word(573, [five,hundred,seventy,three]).
number_word(574, [five,hundred,seventy,four]).
number_word(575, [five,hundred,seventy,five]).
number_word(576, [five,hundred,seventy,six]).
number_word(577, [five,hundred,seventy,seven]).
number_word(578, [five,hundred,seventy,eight]).
number_word(579, [five,hundred,seventy,nine]).
number_word(580, [five,hundred,eighty]).
number_word(581, [five,hundred,eighty,one]).
number_word(582, [five,hundred,eighty,two]).
number_word(583, [five,hundred,eighty,three]).
number_word(584, [five,hundred,eighty,four]).
number_word(585, [five,hundred,eighty,five]).
number_word(586, [five,hundred,eighty,six]).
number_word(587, [five,hundred,eighty,seven]).
number_word(588, [five,hundred,eighty,eight]).
number_word(589, [five,hundred,eighty,nine]).
number_word(590, [five,hundred,ninety]).
number_word(591, [five,hundred,ninety,one]).
number_word(592, [five,hundred,ninety,two]).
number_word(593, [five,hundred,ninety,three]).
number_word(594, [five,hundred,ninety,four]).
number_word(595, [five,hundred,ninety,five]).
number_word(596, [five,hundred,ninety,six]).
number_word(597, [five,hundred,ninety,seven]).
number_word(598, [five,hundred,ninety,eight]).
number_word(599, [five,hundred,ninety,nine]).
number_word(600, [six,hundred]).
number_word(601, [six,hundred,one]).
number_word(602, [six,hundred,two]).
number_word(603, [six,hundred,three]).
number_word(604, [six,hundred,four]).
number_word(605, [six,hundred,five]).
number_word(606, [six,hundred,six]).
number_word(607, [six,hundred,seven]).
number_word(608, [six,hundred,eight]).
number_word(609, [six,hundred,nine]).
number_word(610, [six,hundred,ten]).
number_word(611, [six,hundred,eleven]).
number_word(612, [six,hundred,twelve]).
number_word(613, [six,hundred,thirteen]).
number_word(614, [six,hundred,fourteen]).
number_word(615, [six,hundred,fifteen]).
number_word(616, [six,hundred,sixteen]).
number_word(617, [six,hundred,seventeen]).
number_word(618, [six,hundred,eighteen]).
number_word(619, [six,hundred,nineteen]).
number_word(620, [six,hundred,twenty]).
number_word(621, [six,hundred,twenty,one]).
number_word(622, [six,hundred,twenty,two]).
number_word(623, [six,hundred,twenty,three]).
number_word(624, [six,hundred,twenty,four]).
number_word(625, [six,hundred,twenty,five]).
number_word(626, [six,hundred,twenty,six]).
number_word(627, [six,hundred,twenty,seven]).
number_word(628, [six,hundred,twenty,eight]).
number_word(629, [six,hundred,twenty,nine]).
number_word(630, [six,hundred,thirty]).
number_word(631, [six,hundred,thirty,one]).
number_word(632, [six,hundred,thirty,two]).
number_word(633, [six,hundred,thirty,three]).
number_word(634, [six,hundred,thirty,four]).
number_word(635, [six,hundred,thirty,five]).
number_word(636, [six,hundred,thirty,six]).
number_word(637, [six,hundred,thirty,seven]).
number_word(638, [six,hundred,thirty,eight]).
number_word(639, [six,hundred,thirty,nine]).
number_word(640, [six,hundred,forty]).
number_word(641, [six,hundred,forty,one]).
number_word(642, [six,hundred,forty,two]).
number_word(643, [six,hundred,forty,three]).
number_word(644, [six,hundred,forty,four]).
number_word(645, [six,hundred,forty,five]).
number_word(646, [six,hundred,forty,six]).
number_word(647, [six,hundred,forty,seven]).
number_word(648, [six,hundred,forty,eight]).
number_word(649, [six,hundred,forty,nine]).
number_word(650, [six,hundred,fifty]).
number_word(651, [six,hundred,fifty,one]).
number_word(652, [six,hundred,fifty,two]).
number_word(653, [six,hundred,fifty,three]).
number_word(654, [six,hundred,fifty,four]).
number_word(655, [six,hundred,fifty,five]).
number_word(656, [six,hundred,fifty,six]).
number_word(657, [six,hundred,fifty,seven]).
number_word(658, [six,hundred,fifty,eight]).
number_word(659, [six,hundred,fifty,nine]).
number_word(660, [six,hundred,sixty]).
number_word(661, [six,hundred,sixty,one]).
number_word(662, [six,hundred,sixty,two]).
number_word(663, [six,hundred,sixty,three]).
number_word(664, [six,hundred,sixty,four]).
number_word(665, [six,hundred,sixty,five]).
number_word(666, [six,hundred,sixty,six]).
number_word(667, [six,hundred,sixty,seven]).
number_word(668, [six,hundred,sixty,eight]).
number_word(669, [six,hundred,sixty,nine]).
number_word(670, [six,hundred,seventy]).
number_word(671, [six,hundred,seventy,one]).
number_word(672, [six,hundred,seventy,two]).
number_word(673, [six,hundred,seventy,three]).
number_word(674, [six,hundred,seventy,four]).
number_word(675, [six,hundred,seventy,five]).
number_word(676, [six,hundred,seventy,six]).
number_word(677, [six,hundred,seventy,seven]).
number_word(678, [six,hundred,seventy,eight]).
number_word(679, [six,hundred,seventy,nine]).
number_word(680, [six,hundred,eighty]).
number_word(681, [six,hundred,eighty,one]).
number_word(682, [six,hundred,eighty,two]).
number_word(683, [six,hundred,eighty,three]).
number_word(684, [six,hundred,eighty,four]).
number_word(685, [six,hundred,eighty,five]).
number_word(686, [six,hundred,eighty,six]).
number_word(687, [six,hundred,eighty,seven]).
number_word(688, [six,hundred,eighty,eight]).
number_word(689, [six,hundred,eighty,nine]).
number_word(690, [six,hundred,ninety]).
number_word(691, [six,hundred,ninety,one]).
number_word(692, [six,hundred,ninety,two]).
number_word(693, [six,hundred,ninety,three]).
number_word(694, [six,hundred,ninety,four]).
number_word(695, [six,hundred,ninety,five]).
number_word(696, [six,hundred,ninety,six]).
number_word(697, [six,hundred,ninety,seven]).
number_word(698, [six,hundred,ninety,eight]).
number_word(699, [six,hundred,ninety,nine]).
number_word(700, [seven,hundred]).
number_word(701, [seven,hundred,one]).
number_word(702, [seven,hundred,two]).
number_word(703, [seven,hundred,three]).
number_word(704, [seven,hundred,four]).
number_word(705, [seven,hundred,five]).
number_word(706, [seven,hundred,six]).
number_word(707, [seven,hundred,seven]).
number_word(708, [seven,hundred,eight]).
number_word(709, [seven,hundred,nine]).
number_word(710, [seven,hundred,ten]).
number_word(711, [seven,hundred,eleven]).
number_word(712, [seven,hundred,twelve]).
number_word(713, [seven,hundred,thirteen]).
number_word(714, [seven,hundred,fourteen]).
number_word(715, [seven,hundred,fifteen]).
number_word(716, [seven,hundred,sixteen]).
number_word(717, [seven,hundred,seventeen]).
number_word(718, [seven,hundred,eighteen]).
number_word(719, [seven,hundred,nineteen]).
number_word(720, [seven,hundred,twenty]).
number_word(721, [seven,hundred,twenty,one]).
number_word(722, [seven,hundred,twenty,two]).
number_word(723, [seven,hundred,twenty,three]).
number_word(724, [seven,hundred,twenty,four]).
number_word(725, [seven,hundred,twenty,five]).
number_word(726, [seven,hundred,twenty,six]).
number_word(727, [seven,hundred,twenty,seven]).
number_word(728, [seven,hundred,twenty,eight]).
number_word(729, [seven,hundred,twenty,nine]).
number_word(730, [seven,hundred,thirty]).
number_word(731, [seven,hundred,thirty,one]).
number_word(732, [seven,hundred,thirty,two]).
number_word(733, [seven,hundred,thirty,three]).
number_word(734, [seven,hundred,thirty,four]).
number_word(735, [seven,hundred,thirty,five]).
number_word(736, [seven,hundred,thirty,six]).
number_word(737, [seven,hundred,thirty,seven]).
number_word(738, [seven,hundred,thirty,eight]).
number_word(739, [seven,hundred,thirty,nine]).
number_word(740, [seven,hundred,forty]).
number_word(741, [seven,hundred,forty,one]).
number_word(742, [seven,hundred,forty,two]).
number_word(743, [seven,hundred,forty,three]).
number_word(744, [seven,hundred,forty,four]).
number_word(745, [seven,hundred,forty,five]).
number_word(746, [seven,hundred,forty,six]).
number_word(747, [seven,hundred,forty,seven]).
number_word(748, [seven,hundred,forty,eight]).
number_word(749, [seven,hundred,forty,nine]).
number_word(750, [seven,hundred,fifty]).
number_word(751, [seven,hundred,fifty,one]).
number_word(752, [seven,hundred,fifty,two]).
number_word(753, [seven,hundred,fifty,three]).
number_word(754, [seven,hundred,fifty,four]).
number_word(755, [seven,hundred,fifty,five]).
number_word(756, [seven,hundred,fifty,six]).
number_word(757, [seven,hundred,fifty,seven]).
number_word(758, [seven,hundred,fifty,eight]).
number_word(759, [seven,hundred,fifty,nine]).
number_word(760, [seven,hundred,sixty]).
number_word(761, [seven,hundred,sixty,one]).
number_word(762, [seven,hundred,sixty,two]).
number_word(763, [seven,hundred,sixty,three]).
number_word(764, [seven,hundred,sixty,four]).
number_word(765, [seven,hundred,sixty,five]).
number_word(766, [seven,hundred,sixty,six]).
number_word(767, [seven,hundred,sixty,seven]).
number_word(768, [seven,hundred,sixty,eight]).
number_word(769, [seven,hundred,sixty,nine]).
number_word(770, [seven,hundred,seventy]).
number_word(771, [seven,hundred,seventy,one]).
number_word(772, [seven,hundred,seventy,two]).
number_word(773, [seven,hundred,seventy,three]).
number_word(774, [seven,hundred,seventy,four]).
number_word(775, [seven,hundred,seventy,five]).
number_word(776, [seven,hundred,seventy,six]).
number_word(777, [seven,hundred,seventy,seven]).
number_word(778, [seven,hundred,seventy,eight]).
number_word(779, [seven,hundred,seventy,nine]).
number_word(780, [seven,hundred,eighty]).
number_word(781, [seven,hundred,eighty,one]).
number_word(782, [seven,hundred,eighty,two]).
number_word(783, [seven,hundred,eighty,three]).
number_word(784, [seven,hundred,eighty,four]).
number_word(785, [seven,hundred,eighty,five]).
number_word(786, [seven,hundred,eighty,six]).
number_word(787, [seven,hundred,eighty,seven]).
number_word(788, [seven,hundred,eighty,eight]).
number_word(789, [seven,hundred,eighty,nine]).
number_word(790, [seven,hundred,ninety]).
number_word(791, [seven,hundred,ninety,one]).
number_word(792, [seven,hundred,ninety,two]).
number_word(793, [seven,hundred,ninety,three]).
number_word(794, [seven,hundred,ninety,four]).
number_word(795, [seven,hundred,ninety,five]).
number_word(796, [seven,hundred,ninety,six]).
number_word(797, [seven,hundred,ninety,seven]).
number_word(798, [seven,hundred,ninety,eight]).
number_word(799, [seven,hundred,ninety,nine]).
number_word(800, [eight,hundred]).
number_word(801, [eight,hundred,one]).
number_word(802, [eight,hundred,two]).
number_word(803, [eight,hundred,three]).
number_word(804, [eight,hundred,four]).
number_word(805, [eight,hundred,five]).
number_word(806, [eight,hundred,six]).
number_word(807, [eight,hundred,seven]).
number_word(808, [eight,hundred,eight]).
number_word(809, [eight,hundred,nine]).
number_word(810, [eight,hundred,ten]).
number_word(811, [eight,hundred,eleven]).
number_word(812, [eight,hundred,twelve]).
number_word(813, [eight,hundred,thirteen]).
number_word(814, [eight,hundred,fourteen]).
number_word(815, [eight,hundred,fifteen]).
number_word(816, [eight,hundred,sixteen]).
number_word(817, [eight,hundred,seventeen]).
number_word(818, [eight,hundred,eighteen]).
number_word(819, [eight,hundred,nineteen]).
number_word(820, [eight,hundred,twenty]).
number_word(821, [eight,hundred,twenty,one]).
number_word(822, [eight,hundred,twenty,two]).
number_word(823, [eight,hundred,twenty,three]).
number_word(824, [eight,hundred,twenty,four]).
number_word(825, [eight,hundred,twenty,five]).
number_word(826, [eight,hundred,twenty,six]).
number_word(827, [eight,hundred,twenty,seven]).
number_word(828, [eight,hundred,twenty,eight]).
number_word(829, [eight,hundred,twenty,nine]).
number_word(830, [eight,hundred,thirty]).
number_word(831, [eight,hundred,thirty,one]).
number_word(832, [eight,hundred,thirty,two]).
number_word(833, [eight,hundred,thirty,three]).
number_word(834, [eight,hundred,thirty,four]).
number_word(835, [eight,hundred,thirty,five]).
number_word(836, [eight,hundred,thirty,six]).
number_word(837, [eight,hundred,thirty,seven]).
number_word(838, [eight,hundred,thirty,eight]).
number_word(839, [eight,hundred,thirty,nine]).
number_word(840, [eight,hundred,forty]).
number_word(841, [eight,hundred,forty,one]).
number_word(842, [eight,hundred,forty,two]).
number_word(843, [eight,hundred,forty,three]).
number_word(844, [eight,hundred,forty,four]).
number_word(845, [eight,hundred,forty,five]).
number_word(846, [eight,hundred,forty,six]).
number_word(847, [eight,hundred,forty,seven]).
number_word(848, [eight,hundred,forty,eight]).
number_word(849, [eight,hundred,forty,nine]).
number_word(850, [eight,hundred,fifty]).
number_word(851, [eight,hundred,fifty,one]).
number_word(852, [eight,hundred,fifty,two]).
number_word(853, [eight,hundred,fifty,three]).
number_word(854, [eight,hundred,fifty,four]).
number_word(855, [eight,hundred,fifty,five]).
number_word(856, [eight,hundred,fifty,six]).
number_word(857, [eight,hundred,fifty,seven]).
number_word(858, [eight,hundred,fifty,eight]).
number_word(859, [eight,hundred,fifty,nine]).
number_word(860, [eight,hundred,sixty]).
number_word(861, [eight,hundred,sixty,one]).
number_word(862, [eight,hundred,sixty,two]).
number_word(863, [eight,hundred,sixty,three]).
number_word(864, [eight,hundred,sixty,four]).
number_word(865, [eight,hundred,sixty,five]).
number_word(866, [eight,hundred,sixty,six]).
number_word(867, [eight,hundred,sixty,seven]).
number_word(868, [eight,hundred,sixty,eight]).
number_word(869, [eight,hundred,sixty,nine]).
number_word(870, [eight,hundred,seventy]).
number_word(871, [eight,hundred,seventy,one]).
number_word(872, [eight,hundred,seventy,two]).
number_word(873, [eight,hundred,seventy,three]).
number_word(874, [eight,hundred,seventy,four]).
number_word(875, [eight,hundred,seventy,five]).
number_word(876, [eight,hundred,seventy,six]).
number_word(877, [eight,hundred,seventy,seven]).
number_word(878, [eight,hundred,seventy,eight]).
number_word(879, [eight,hundred,seventy,nine]).
number_word(880, [eight,hundred,eighty]).
number_word(881, [eight,hundred,eighty,one]).
number_word(882, [eight,hundred,eighty,two]).
number_word(883, [eight,hundred,eighty,three]).
number_word(884, [eight,hundred,eighty,four]).
number_word(885, [eight,hundred,eighty,five]).
number_word(886, [eight,hundred,eighty,six]).
number_word(887, [eight,hundred,eighty,seven]).
number_word(888, [eight,hundred,eighty,eight]).
number_word(889, [eight,hundred,eighty,nine]).
number_word(890, [eight,hundred,ninety]).
number_word(891, [eight,hundred,ninety,one]).
number_word(892, [eight,hundred,ninety,two]).
number_word(893, [eight,hundred,ninety,three]).
number_word(894, [eight,hundred,ninety,four]).
number_word(895, [eight,hundred,ninety,five]).
number_word(896, [eight,hundred,ninety,six]).
number_word(897, [eight,hundred,ninety,seven]).
number_word(898, [eight,hundred,ninety,eight]).
number_word(899, [eight,hundred,ninety,nine]).
number_word(900, [nine,hundred]).
number_word(901, [nine,hundred,one]).
number_word(902, [nine,hundred,two]).
number_word(903, [nine,hundred,three]).
number_word(904, [nine,hundred,four]).
number_word(905, [nine,hundred,five]).
number_word(906, [nine,hundred,six]).
number_word(907, [nine,hundred,seven]).
number_word(908, [nine,hundred,eight]).
number_word(909, [nine,hundred,nine]).
number_word(910, [nine,hundred,ten]).
number_word(911, [nine,hundred,eleven]).
number_word(912, [nine,hundred,twelve]).
number_word(913, [nine,hundred,thirteen]).
number_word(914, [nine,hundred,fourteen]).
number_word(915, [nine,hundred,fifteen]).
number_word(916, [nine,hundred,sixteen]).
number_word(917, [nine,hundred,seventeen]).
number_word(918, [nine,hundred,eighteen]).
number_word(919, [nine,hundred,nineteen]).
number_word(920, [nine,hundred,twenty]).
number_word(921, [nine,hundred,twenty,one]).
number_word(922, [nine,hundred,twenty,two]).
number_word(923, [nine,hundred,twenty,three]).
number_word(924, [nine,hundred,twenty,four]).
number_word(925, [nine,hundred,twenty,five]).
number_word(926, [nine,hundred,twenty,six]).
number_word(927, [nine,hundred,twenty,seven]).
number_word(928, [nine,hundred,twenty,eight]).
number_word(929, [nine,hundred,twenty,nine]).
number_word(930, [nine,hundred,thirty]).
number_word(931, [nine,hundred,thirty,one]).
number_word(932, [nine,hundred,thirty,two]).
number_word(933, [nine,hundred,thirty,three]).
number_word(934, [nine,hundred,thirty,four]).
number_word(935, [nine,hundred,thirty,five]).
number_word(936, [nine,hundred,thirty,six]).
number_word(937, [nine,hundred,thirty,seven]).
number_word(938, [nine,hundred,thirty,eight]).
number_word(939, [nine,hundred,thirty,nine]).
number_word(940, [nine,hundred,forty]).
number_word(941, [nine,hundred,forty,one]).
number_word(942, [nine,hundred,forty,two]).
number_word(943, [nine,hundred,forty,three]).
number_word(944, [nine,hundred,forty,four]).
number_word(945, [nine,hundred,forty,five]).
number_word(946, [nine,hundred,forty,six]).
number_word(947, [nine,hundred,forty,seven]).
number_word(948, [nine,hundred,forty,eight]).
number_word(949, [nine,hundred,forty,nine]).
number_word(950, [nine,hundred,fifty]).
number_word(951, [nine,hundred,fifty,one]).
number_word(952, [nine,hundred,fifty,two]).
number_word(953, [nine,hundred,fifty,three]).
number_word(954, [nine,hundred,fifty,four]).
number_word(955, [nine,hundred,fifty,five]).
number_word(956, [nine,hundred,fifty,six]).
number_word(957, [nine,hundred,fifty,seven]).
number_word(958, [nine,hundred,fifty,eight]).
number_word(959, [nine,hundred,fifty,nine]).
number_word(960, [nine,hundred,sixty]).
number_word(961, [nine,hundred,sixty,one]).
number_word(962, [nine,hundred,sixty,two]).
number_word(963, [nine,hundred,sixty,three]).
number_word(964, [nine,hundred,sixty,four]).
number_word(965, [nine,hundred,sixty,five]).
number_word(966, [nine,hundred,sixty,six]).
number_word(967, [nine,hundred,sixty,seven]).
number_word(968, [nine,hundred,sixty,eight]).
number_word(969, [nine,hundred,sixty,nine]).
number_word(970, [nine,hundred,seventy]).
number_word(971, [nine,hundred,seventy,one]).
number_word(972, [nine,hundred,seventy,two]).
number_word(973, [nine,hundred,seventy,three]).
number_word(974, [nine,hundred,seventy,four]).
number_word(975, [nine,hundred,seventy,five]).
number_word(976, [nine,hundred,seventy,six]).
number_word(977, [nine,hundred,seventy,seven]).
number_word(978, [nine,hundred,seventy,eight]).
number_word(979, [nine,hundred,seventy,nine]).
number_word(980, [nine,hundred,eighty]).
number_word(981, [nine,hundred,eighty,one]).
number_word(982, [nine,hundred,eighty,two]).
number_word(983, [nine,hundred,eighty,three]).
number_word(984, [nine,hundred,eighty,four]).
number_word(985, [nine,hundred,eighty,five]).
number_word(986, [nine,hundred,eighty,six]).
number_word(987, [nine,hundred,eighty,seven]).
number_word(988, [nine,hundred,eighty,eight]).
number_word(989, [nine,hundred,eighty,nine]).
number_word(990, [nine,hundred,ninety]).
number_word(991, [nine,hundred,ninety,one]).
number_word(992, [nine,hundred,ninety,two]).
number_word(993, [nine,hundred,ninety,three]).
number_word(994, [nine,hundred,ninety,four]).
number_word(995, [nine,hundred,ninety,five]).
number_word(996, [nine,hundred,ninety,six]).
number_word(997, [nine,hundred,ninety,seven]).
number_word(998, [nine,hundred,ninety,eight]).
number_word(999, [nine,hundred,ninety,nine]).
number_word(1000, [one,thousand]).

        
        
    
    
    
